### ISSUE TITLE
Expose driver Web UI port as NodePort

### ISSUE THREAD

**Issue by kimoonkim** [apache-spark-on-k8s/spark#129]
@ash211 

I was hoping to look at the driver Web UI from my browser. Then found the Web UI port is specified only as ClusterIP in [Client.scala](https://github.com/apache-spark-on-k8s/spark/blob/k8s-support-alternate-incremental/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala#L235).  I wonder if we want to set it as a NodePort at least so human users can take a look?
```
    kubernetesClient.services().withName(kubernetesAppId).edit().editSpec()
      .withType("ClusterIP")
      .withPorts(uiServicePort)
      .endSpec()
      .done()
```

The change seems simple. My local patch just replacing `"ClusterIP"` above with `"NodePort"` fixed it. Is this the right way? If yes, I can send a PR.

**Comment by mccheah** [comment]
The problem with NodePort is that it's a limited resource. Since a port is allocated on every node of the cluster, the clusters need to have a wide enough range of ports that can be opened to serve the UIs in question.

A solution is to instead use an Ingress. I have proposed this in #116, but it requires an Ingress controller implementation to be configured on the cluster. Perhaps we should have a configuration option to support exposing the UI over node port, but set it to off by default.

**Comment by kimoonkim** [comment]
Thanks for the reasoning @mccheah. We don't have Ingress in our cluster. But I agree It makes sense to expose the UI NodePort only as an option. I'll see if I can write a small PR doing just that.

**Comment by ash211** [comment]
Fixed in https://github.com/apache-spark-on-k8s/spark/pull/131
