### ISSUE TITLE
Replace usage of API server proxy in Client with Ingress or NodePort

### ISSUE THREAD

**Issue by mccheah** [apache-spark-on-k8s/spark#24]
Currently the K8s client running on the user's machine contacts the REST server to submit local files and other configurations. The Client uses the API server proxy to reach the service endpoint. We could think about whether or not we want to replace the usage of the proxy with either an Ingress proxy or exposing the service on a node port. The tradeoffs between these three different alternatives should be weighed before we move forward with one of them.

**Comment by mccheah** [comment]
@foxish @erikerlandson what are your thoughts on the different options here?

**Comment by foxish** [comment]
There are trade-offs here. The APIServer proxy won't scale and will overload the master, so it would be best to move away from it for submitting large files. The LoadBalancer and Ingress resources are not necessarily supported on all clusters, so that makes them a little less preferable in my opinion. NodePort to me seems like a viable alternative. However, it has the unfortunate side effect of exposing one port on all nodes and placing an upper limit on the number of running drivers in a cluster. That might not really be an issue however. We would need to figure out authentication ourselves in that case, and a way to shut down and stop listening on that NodePort as soon as file submission completes. 

Do we have an idea of how large the files submitted by the client may be?

**Comment by mccheah** [comment]
As large as it would take to store an entire application's custom jars. We do gzip compress the shipped contents, but I agree we would want something that scales better.

Is there a timeline for supporting Ingress everywhere and having it on by default?

Edit: Does the story change if we also say we want to SSL encrypt the shipped jars? I would imagine it would be trickier to get this right with the API server proxy as well. I'm not sure if it makes a difference for either the Ingress or the NodePort approach. Ingress does support SSL termination but it would be nice to get the SSL encryption end to end all the way to the driver pod itself.

**Comment by foxish** [comment]
I'm going to look at the networking SIG's mandate. I'll get back to this issue once I talk to folks from the SIG.
Submitting local jars is just one possible mechanism, and I expect that baking the jars into the image, or using HDFS/network storage to store jars will be the major use case. 

If we are going to use authentication and nodeports, I'm wondering if it might make sense to have one submission server per cluster (rather than per driver), like the model that https://github.com/spark-jobserver/spark-jobserver uses. Thoughts?

**Comment by mccheah** [comment]
Having one submission server for the whole cluster could also work, but it would require the extra deployment step to set it up on the user's part. Having the spark-submit procedure set up everything automatically I think would be a more ideal experience.

What have been some of the usual ways that SSL has been set up on Kubernetes services in general?

**Comment by foxish** [comment]
>Having one submission server for the whole cluster could also work, but it would require the extra deployment step to set it up on the user's part. Having the spark-submit procedure set up everything automatically I think would be a more ideal experience.

I agree that it would be more seamless. However, if we do require the submission server to exist, it would need to be setup once by the cluster administrator, which is not necessarily bad. I think Mesos on Spark uses this model. 

SSL setup: using the nginx ssl proxy https://github.com/GoogleCloudPlatform/nginx-ssl-proxy is a common way to go about that.

**Comment by mccheah** [comment]
Actually I'm not sure if the singleton submission server works in our case. The reason is that we're trying to deploy the user's jars onto the local disk of the driver that ends up running. If the driver runs in its own pod, the submission server needs to be running with a disk shared to the driver pod. But of course since each driver runs in its own pod, that means each driver needs to have its own submission server.

**Comment by foxish** [comment]
I was expecting that such a singleton submission server would work exactly the same as the APIServer proxy, proxying content to each possible driver pod.

**Comment by mccheah** [comment]
The driver pod would still need to have a server to receive the content. In such a case I don't see what the singleton submission server which is acting as a proxy would do that cannot be accomplished by using Kubernetes primitives such as services and Ingress. Is there an advantage to using our own proxy server as opposed to leveraging what Kubernetes already provides?

**Comment by foxish** [comment]
> The driver pod would still need to have a server to receive the content.

Yes, but that IP:port would not need to be exposed outside the cluster. Ingress and LoadBalancer currently work as abstractions over NodePort and need specific cloud provider support to work. So, the question is whether we want one NodePort allocated per driver, or one NodePort per cluster for a Spark submission proxy. I summarized the two approaches below. 

1. One submission service per driver (current model)
   * Simpler as we are launching the server and client with each spark-submit 
   * We need as many NodePorts to be opened as there are SparkJobs uploading local JARs. 
   * By default, there are only around [2700 ports](https://kubernetes.io/docs/user-guide/services/#type-nodeport) that can be used by default, and they're a cluster-wide resource.
   * We do not want to impact multi-tenancy adversely by occupying too many NodePorts, because it is a cluster-wide resource.

2. One submission service for the entire cluster
    * We need exactly one NodePort to be exposed outside the cluster.
    * This proxy would need to authenticate on behalf of the user and proxy files to any driver pod.
    * We can scale this proxy up/down independently depending on the load

I think we should pick according to how long we expect the NodePort service to live. If we ensure that the lifetime of the service is very short, we can do one NodePort per driver. There may be performance implications of having a large number of services (1000s), but we haven't done a scalability test yet to confirm.

**Comment by foxish** [comment]
I had a discussion with some networking folks. There are no scalability limits that we know of, so, we should be okay with one NodePort per driver, as long as we return it back to the allocator pool as soon as uploading of local jars is complete. Keeping the service around for the entirety of the driver's lifetime would definitely make us hit NodePort limits rather quickly.

**Comment by mccheah** [comment]
The NodePort for the submission would be fairly short lived as it only needs to upload the data to the driver. We can open the port for the duration of the submission and then close it when we're done. This wouldn't scale if someone submits a large number of Spark jobs in quick succession though, causing the port space to run out.

There is also something to be said about the Spark UI, which is long-lived. We will probably want to have a proxy server for that, perhaps as part of the work we're doing around creating Spark-based constructs in core Kubernetes, etc.

**Comment by mccheah** [comment]
The more I'm thinking about this though the more I'm liking the idea of building our own proxy service, because of the use case of burst-submits of jobs which I think may actually be quite common. It could be fairly lightweight as well and doesn't actually have to handle much of the authentication matters since this server wouldn't be responsible for the creation of any Kubernetes resources but would just be handed a pod/service IP to forward the submission request to, as well as the certificate that the driver generated for that submission.

Edit: It would be nice to use something simple like Nginx but unfortunately I think the two hops of SSL will make it difficult, particularly since all of the drivers would ideally have unique credentials.

**Comment by foxish** [comment]
We should have around 2000 ports available for use by default (and can be raised to 10,000 or higher using an argument to the master). For a burst submission to use up all of those ports, all of those jobs would need to be trying to upload jars concurrently. Do you see that being a likely scenario? From talking to people, it doesn't seem like that would be common.

**Comment by mccheah** [comment]
Hm, yeah perhaps it won't be that common.

We would probably need to build a proxy server to handle the Spark UI case anyways. Perhaps we can revisit the discussion of proxying the file uploads through that when we build that out. For V0 I think NodePort is sufficient.

**Comment by ash211** [comment]
I'm not thinking 2000+ concurrent apps would be all that common either.  Maybe instead of using highly concurrent apps as a use case driving a decision to move between API server proxy vs ingress vs nodeport, we use the Spark UI as the motivating use case.

I think that's something we can pick up in #22 since the kubernetes dashboard and Spark UI are related (both aim to make Spark app diagnostics available in a webui)

**Comment by mccheah** [comment]
Basically we adopt a wait-and-see approach and we can adjust the direction if we get concerns about scaling the job submission.

One quick question - does editing the service spec to remove the node port return the port to the pool?

**Comment by foxish** [comment]
>One quick question - does editing the service spec to remove the node port return the port to the pool?

Yes, if you mean changing the .Spec.Type from NodePort to ClusterIP or None. 
If we delete the service, the port is returned to the pool. I think I don't understand the use case here, around editing the service spec.

@ash211 That is a good point. We'll certainly need a proxy for displaying the SparkUI since it is expected to be up for as long as the job itself.

**Comment by mccheah** [comment]
Yes I meant changing the type to ClusterIP. Cool - I'll start implementing this.

**Comment by foxish** [comment]
We've been thinking more about this, and the possibility of tackling this problem for the general use case by designing an application proxy.
As for the shorter time frame and the prototype, I'm thinking that NodePort for the SubmissionServer and APIServer proxy to serve up the SparkUI pages (which are pretty tiny) should be okay.

**Comment by mccheah** [comment]
@foxish - I was thinking about this a little more and I'm leaning more towards a proxy-based approach - requiring the deployment of a proxy or a “submission server”. The reason is to support use cases where Kubernetes hosts are not routable from outside the cluster. The usage of NodePort is sufficient for cases where the Kubelet hostnames are DNS resolvable by the client, but that might not necessarily be the case. Being able to submit applications in these situations would require some kind of gateway that can forward the submit request to the driver. The proxy-based approach seems to provide that gateway.  What do you think?

One thing to consider with this submission server approach - what should handle most of the logic of talking to the API server and creating the driver Kubernetes resources, the pod and service? One could imagine a world where spark-submit does minimal work on the client machine and a central submission server creates all the resources - but I'm hesitant about doing this because the central submission server would need to be given the credentials from the client. There would also need to be a division of logic between the submission server and the client (spark-submit), whereas with the client handling all the K8s communications, we can make the proxy server as lightweight as just an intelligently-configured Nginx, which we can provide in a Dockerfile.

As we've been considering this along with SSL it seems that there's some nuances in the complexity here and we should try to work these out and cover all our bases. Perhaps we could schedule a discussion over a higher-bandwidth channel next week on the matter?

**Comment by mccheah** [comment]
Discussed offline - we should expect Spark submitters to be able to access the kubelets in the cluster and thus access the driver pod's server over NodePort. We can later on support an alternative mode of operation where the jars are shipped through the API server proxy, but we can afford to defer on this for now in order to reduce the config surface area for the MVP. In particular, #28 is easier to reason about with only one supported path.
