### ISSUE TITLE
Jenkins is down?

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#267]
http://spark-k8s-jenkins.pepperdata.org:8080/ is inaccessible and CI jobs aren't running anymore.

cc @ssuchter @varunkatta @kimoonkim

**Comment by ssuchter** [comment]
Hm, looking

**Comment by foxish** [comment]
Thanks!

**Comment by ssuchter** [comment]
Please try again. For some reason the jenkins process died, don’t know why.

**Comment by foxish** [comment]
@ssuchter @varunkatta appears that the process has died again.

**Comment by tnachen** [comment]
@ssuchter @varunkatta btw I have a CI system that has minikube available donated by the folks from  Applatix, we can use it to run unit tests on PR instead of we're hoping some other managed SaaS to manage this.

**Comment by cvpatel** [comment]
@foxish I restarted the process last night; seems to be running fine now. It seems like the jenkins process was stuck... Will dive a bit deeper if it continues to have issues.

**Comment by ssuchter** [comment]
We can give more people logins (so you can restart jobs, etc) We can’t just
open it up publicly. Anyone who is regularly using it, we should just add
them. Matt? Andrew? Anirudh?

Sean

On May 15, 2017 at 9:37:36 AM, Chaitanya Patel (notifications@github.com)
wrote:

@foxish <https://github.com/foxish> I restarted the process last night;
seems to be running fine now. It seems like the jenkins process was
stuck... Will dive a bit deeper if it continues to have issues.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark/issues/267#issuecomment-301530956>,
or mute the thread

**Comment by ash211** [comment]
It would be helpful for Matt and me to have some level of access to the Jenkins jobs.

One thing we're about to open a ticket up for anyway that's would require Jenkins changes is modifying the way tests are run, to be via SBT instead of via Maven to be more compatible with Apache Spark

**Comment by ssuchter** [comment]
Ok, I’ll make ash211 and mccheah. Can you give me an out-of-band way to
tell you an initial password. (Or send me your public key and I’ll send it
to you encrypted.) Of course you will change the password later.

Sean

On May 15, 2017 at 12:02:21 PM, Andrew Ash (notifications@github.com) wrote:

It would be helpful for Matt and me to have some level of access to the
Jenkins jobs.

One thing we're about to open a ticket up for anyway that's would require
Jenkins changes is modifying the way tests are run, to be via SBT instead
of via Maven to be more compatible with Apache Spark

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark/issues/267#issuecomment-301572059>,
or mute the thread

**Comment by ash211** [comment]
(followed up offline)

**Comment by ash211** [comment]
@foxish I think we can close this now -- the original issue seemed like a one-off and we're taking steps to reduce breakage in CI infra via #279 and #280

**Comment by foxish** [comment]
It appears to be down again. PTAL @ssuchter @varunkatta @kimoonkim

**Comment by kimoonkim** [comment]
I see. Looking.

**Comment by kimoonkim** [comment]
It should be up now.
