### ISSUE TITLE
what benefits to spark itself?

### ISSUE THREAD

**Issue by FANNG1** [apache-spark-on-k8s/spark#270]
co running docker app and spark app is really great work. I wondered is there any other benefit to use k8s not using yarn/mesos/standalone mode?

**Comment by mccheah** [comment]
@sandflee The primary target here is optionality. Users that are looking to use Kubernetes for their other workloads ought to be able to use the same cluster management framework for their Spark workloads as well. In such scenarios, the user may have already evaluated YARN and Mesos and determined that Kubernetes is preferable over those other cluster managers for reasons that are independent of Spark. Such reasons may be more of a question of which cluster manager to use in and of themselves, rather than their particular relationship to Spark.

**Comment by kimoonkim** [comment]
On top of @mccheah's points. My 2 cent is that Spark itself can benefit from more isolation coming from dockers. Many of us have this bad experience like "my Spark job started to crash with `ClassNotFound` exception after someone installed a different version of spark packages". Docker solves this problem fundamentally. This other person will install new packages in a different docker image and affect only his Spark job in separate pods, not mine.  For many ops and devs with multi-tenant clusters, this could be nice.

**Comment by lins05** [comment]
+1 @mccheah @kimoonkim 

@kimoonkim Spark on mesos supports running driver/executors in docker containers as well. The only downside is the driver/executor containers must all run in host network mode.

**Comment by kimoonkim** [comment]
@lins05 Ah, good to know. I knew mesos supports dockers, but I didn't know the details.

**Comment by FANNG1** [comment]
thanks all :)

**Comment by ash211** [comment]
Hope that was useful @sandflee !

The big value-add I'm interested in is the isolation between users on the same cluster by virtue of the containerized separation.  This prevents e.g. a rogue application from stealing credentials from a neighbor job on the same server.

**Comment by jian-he** [comment]
FWIW, YARN also supports running docker containers in a native way.

**Comment by mccheah** [comment]
There are some notable differences between how YARN handles Docker versus how Kubernetes handles Docker. For example, the security and isolation model is different, as YARN cannot use Docker in secure mode, and "...software running as root in the YARN container will have root privileges in the underlying NodeManager": https://hadoop.apache.org/docs/r2.7.2/hadoop-yarn/hadoop-yarn-site/DockerContainerExecutor.html. In contrast to this, Kubernetes has the notion of the security context and is not fundamentally tied to the underlying system users: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/. @foxish might have more information here. I believe the Docker features are being revamped in Hadoop YARN 3.0 as well though.

**Comment by erikerlandson** [comment]
As I understand it, In YARN you can only support a single rev of Spark in the cluster (is this also true of other libraries/deps?).  Kube doesn't have this limitation, since it does not care what software runs on any given container.

**Comment by ssuchter** [comment]
I don’t think this is correct. If you try to get the Spark jars out of what
is installed on the nodes, then you have to use what is installed on the
cluster. But otherwise, spark-submit can get YARN to distribute whatever
jars your version of Spark needs.

https://stackoverflow.com/questions/29691028/can-i-have-multiple-spark-versions-installed-in-cdh

**Comment by mccheah** [comment]
One limitation is that the docker images need to be pre-pulled into the NodeManagers. Kubernetes handles the pulling of the images to the Kubelets.
