### ISSUE TITLE
Watch for service readiness instead of pod readiness 

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#76]
As a follow up to https://github.com/apache-spark-on-k8s/spark/pull/75

Determine whether the watch should be switched from the driver pod passing the readiness check to the service having a live node behind it.

**Comment by lins05** [comment]
I can think of two benefits of using a probe on the service instead of on the pod:

1. Conceptually cleaner, because we'll contact the service's NodePort to submit the request
2. (most likely a corner case) When the service is created, the firewall rules that forward the traffic from the NodePort to the container port may not be installed yet, and using a probe on the service could avoid this?

**Comment by foxish** [comment]
Closing as per discussion in our meeting
