### ISSUE TITLE
Set up CI build (Travis) for testing

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#8]
Always good to have CI running for large projects!  Should include both the unit tests and the integration tests (using minikube).

@erikerlandson suggests Sean has experience here and could help get this going.

**Comment by ssuchter** [comment]
Yep, someone over here will take this one. I'll report back.

**Comment by ash211** [comment]
@ssuchter any progress on this?  We're starting to have a few smaller commits a day and CI assurance is always nice :)

**Comment by ssuchter** [comment]
Not yet, I didn’t realize the urgency - we were going to get to it next
week. The current Spark Jenkins is hosted by Berkeley, so one just add
things to it. We were going to look into using either Travis or us hosting
a Jenkins node. Will looking into this next week be ok?

Sean

On January 11, 2017 at 4:05:57 PM, Andrew Ash (notifications@github.com)
wrote:

@ssuchter <https://github.com/ssuchter> any progress on this? We're
starting to have a few smaller commits a day and CI assurance is always
nice :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark/issues/8#issuecomment-272035833>,
or mute the thread

**Comment by ssuchter** [comment]
We’re looking into it now - update on ETA tomorrow.

Sean

On January 11, 2017 at 4:22:03 PM, Sean Suchter (sean@suchter.com) wrote:

Not yet, I didn’t realize the urgency - we were going to get to it next
week. The current Spark Jenkins is hosted by Berkeley, so one just add
things to it. We were going to look into using either Travis or us hosting
a Jenkins node. Will looking into this next week be ok?

Sean

On January 11, 2017 at 4:05:57 PM, Andrew Ash (notifications@github.com)
wrote:

@ssuchter <https://github.com/ssuchter> any progress on this? We're
starting to have a few smaller commits a day and CI assurance is always
nice :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark/issues/8#issuecomment-272035833>,
or mute the thread

**Comment by ssuchter** [comment]
Heh, fixing the last comment. We did some experimentation last night, and it seems like Travis CI will work well for this. Working on a doc and/or actually setting it up.

**Comment by ssuchter** [comment]
Ok, I've got Travis working on my fork - once I learned how to do it, was very simple.

https://github.com/pepperdata/ssuchter-test-spark
and
https://travis-ci.org/pepperdata/ssuchter-test-spark

I need some minor permissions on the apache-spark-on-k8s project to do it (not code submission, but permissions about creating integration and adding comments to issues, because Travis will want to do it.) I can either describe it to one of you, or I can do it. For now, I'll just send a request for the permissions I need, that might be the simpler way.

**Comment by foxish** [comment]
Approved access! Thanks @ssuchter.

**Comment by ssuchter** [comment]
Grr. Apparently I need to have more access to set this up. I think ultimately we will want a role account for this, but maybe temporarily could someone make my account an "admin" so Travis setup will work? I promise that I won't do anything else and I want to revoke that access later.

See attached image that has the error message:

![apache_spark_on_kubernetes_-_profile_-_travis_ci](https://cloud.githubusercontent.com/assets/1934555/21909808/530d8e54-d8ce-11e6-9342-2ff2b268fe20.png)

**Comment by ssuchter** [comment]
I didn't notice this before because on our organization, I'm already an admin. :/

**Comment by ssuchter** [comment]
Ok, I turned Travis CI on. I've got a couple meetings, but in a little bit I'll try making a dummy pull request to try it out.

**Comment by foxish** [comment]
Sounds good!

**Comment by ssuchter** [comment]
I should note that this is not yet doing anything beyond what the builtin .travis.yml does. We probably need to modify that, and also we will have to work on a minikube based test, as imagined earlier. That's a little more work than just the raw setup.

**Comment by ssuchter** [comment]
BTW, see Travis here: https://travis-ci.org/apache-spark-on-k8s/spark

**Comment by ssuchter** [comment]
Yay, it's working (well at least it's running the tests... we'll see if they succeed soon-ish):

![added_service_name_as_prefix_to_executor_pods_by_foxish_ _pull_request__14_ _apache-spark-on-k8s_spark](https://cloud.githubusercontent.com/assets/1934555/21911364/5729b466-d8d5-11e6-982b-4626f7a9184e.png)

**Comment by kimoonkim** [comment]
Hi, I am working with @ssuchter for the travis CI setup. The current .[travis.yml](https://github.com/apache-spark-on-k8s/spark/blob/k8s-support-alternate-incremental/.travis.yml) file does not use the kubernetes build profile.

 - build/mvn -T 4 -q -DskipTests -Pmesos -Pyarn -Phadoop-2.3 -Pkinesis-asl -Phive -Phive-thriftserver install

I just sent a pull request #21 with a fix adding the profile.

**Comment by ash211** [comment]
This seems to be working and is catching issues -- @kimoonkim I think we're good to close this?  Anything more we ought to do immediately with the `.travis.yml` file?

**Comment by kimoonkim** [comment]
@ash211 Yes. I think we can close this. Sean and I started looking at integration tests, but we should open a new issue when we get it going and have something to discuss. Thanks.
