### ISSUE TITLE
Narrow down the list of Node IPs to external interfaces only

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#90]
Currently, the NodePorts that the client tries to connect to looks like:

```
(http://10.128.0.4:31036 
http://104.198.190.156:31036 
http://kubernetes-minion-group-3pvp:31036 
http://10.128.0.6:31036 
http://104.197.142.73:31036 
http://kubernetes-minion-group-cnk6:31036 
http://10.128.0.5:31036 
http://146.148.100.170:31036 
http://kubernetes-minion-group-j0qh:31036)
```

Each node shows up thrice with hostname, external and internal IPs. We should probably limit it such that we only go over external IP addresses of the nodes.

**Comment by ash211** [comment]
+1 this would alleviate a lot of unnecessary failover between hosts that are known to never function.  For example we would never be able to access the internal IP addresses from the submitter so those should be filtered at a minimum.

@foxish you suggest just external IP instead of the hostname -- do you expect to have problems with the hostname and that's why you suggest just using external IP?

**Comment by foxish** [comment]
The hostname won't work with GCE, GKE, etc typically. The external IP is pretty reliable on the other hand.
